builds:
  - binary: mediumautopost
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: httpurr
    homepage: "https://github.com/rednafi/httpurr"
    tap:
      owner: rednafi
      name: httpurr
    commit_author:
      name: rednafi
      email: redowan.nafi@gmail.com

checksum:
  name_template: 'checksums.txt'
