builds:
  - binary: ./cmd/http-purr
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: httpurr
    homepage: "https://github.com/rednafi/httpurr"
    repository:
      owner: rednafi
      name: httpurr
    commit_author:
      name: rednafi
      email: redowan.nafi@gmail.com

checksum:
  name_template: 'checksums.txt'


# # .goreleaser.yaml
# before:
#   hooks:
#     - go mod tidy
#     - go generate ./...

# builds:
#   - <<: &build_defaults
#       binary: bin/http-purr
#       main: ./cmd/http-purr
#     id: macos
#     goos: [darwin]
#     goarch: [amd64, arm64]
#   - <<: *build_defaults
#     id: linux
#     goos: [linux]
#     goarch: [arm, amd64, arm64]
#     env:
#       - CGO_ENABLED=0

# archives:
#   - id: nix
#     builds: [macos, linux]
#     <<: &archive_defaults
#       name_template: |-
#         'http-purr_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
#     wrap_in_directory: true
#     format: tar.gz
#     files:
#       - LICENSE
#   - id: windows
#     builds: [windows]
#     <<: *archive_defaults
#     wrap_in_directory: false
#     format: zip
#     files:
#       - LICENSE

# release:
#   prerelease: auto

# checksum:
#   name_template: 'checksums.txt'

# snapshot:
#   name_template: '{{ incpatch .Version }}-next'

# changelog:
#   sort: asc
#   filters:
#     exclude:
#       - '^docs:'
#       - '^test:'
